from rng import RNG

bit_len = 40
qrng = RNG(bit_len=bit_len, options='qrng')
print('Quantum random number generator')
print(qrng.generate_random_bits())
print('============================================')
numpy_rng = RNG(bit_len=bit_len, options='numpy')
print('Numpy random number generator')
print(numpy_rng.generate_random_bits())
print('============================================')
os_rng = RNG(bit_len=bit_len, options='os')
print('OS random number generator')
print(os_rng.generate_random_bits())
print('============================================')
secrets_rng = RNG(bit_len=bit_len, options='secrets')
print('Secrets random number generator')
print(secrets_rng.generate_random_bits())
print('============================================')
random_rng = RNG(bit_len=bit_len, options='random')
print('Random random number generator')
print(random_rng.generate_random_bits())
print('============================================')
crypto_rng = RNG(bit_len=bit_len, options='crypto')
print('Crypto random number generator')
print(crypto_rng.generate_random_bits())